### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by AmanWorku** [AmanWorku/Cooks-Corner#12]
## Hello there....
In this Ruby on Rails project we are teams of three: 

- @lawrahkonwea 
- @AmanWorku
- @Thinus01 

Here is the link to our [project page](https://github.com/users/AmanWorku/projects/5)

**Comment by BregornOriginal** [comment]
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn´t contain a link to your GitHub projects

- Kindly, instead add a link to your issues page. Add a link to your GitHub [Project](https://github.com/users/AmanWorku/projects/5)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by addod19** [comment]
### Hi @AmanWorku , @Thinus01 , and @lawrahkonwea, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that is invalid because I'm unable to find a link to the GitHub project as mentioned in the previous invalidation review. Here is an example [link](https://github.com/users/AmanWorku/projects/5)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @AmanWorku, @Thinus01 and @lawrahkonwea,

Good job so far!
✔️ Kanban columns are complete
✔️ Tasks are well assigned
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] These issues (Food list) are only meant for groups with fewer than 3 members but you are 3 in number. Kindly remove them. [Food list](https://github.com/AmanWorku/Cooks-Corner/issues/3) and [General shopping list](https://github.com/AmanWorku/Cooks-Corner/issues/10)

- [ ] You are missing issues for these tasks. Kindly add them.

  ![image](https://user-images.githubusercontent.com/36542986/236846738-75cea6b1-e637-4c64-a472-6c0b1df944b3.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://media1.giphy.com/media/YKdm91XONLTaw/giphy-downsized-medium.gif"/>

## Highlights
- Group work ✔️ 
- Good implementations ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
